[[constraint]]
  name = "github.com/goat-project/goat-proto-go"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = " v1.24.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.3.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"